# Generated by Django 2.1.1 on 2018-09-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_auto_20180914_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponuser',
            name='uses',
        ),
    ]
