# Generated by Django 2.1.1 on 2018-09-14 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20180914_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used',
        ),
        migrations.AlterField(
            model_name='couponuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Customer', verbose_name='Customer'),
        ),
    ]
