# Generated by Django 2.1.1 on 2018-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_auto_20180914_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='uses_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='Uses per user'),
        ),
        migrations.AddField(
            model_name='couponuser',
            name='uses',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
