# Generated by Django 2.1.1 on 2018-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_auto_20180926_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponuser',
            name='uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
