# Generated by Django 2.1.7 on 2019-04-01 13:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190401_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity_fulfilled',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='translated_product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price_gross',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price_net',
        ),
        migrations.RemoveField(
            model_name='orderitemmod',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='orderitemmod',
            name='quantity_fulfilled',
        ),
        migrations.RemoveField(
            model_name='orderitemmod',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='orderitemmod',
            name='translated_product_name',
        ),
        migrations.RemoveField(
            model_name='orderitemmod',
            name='unit_price_gross',
        ),
        migrations.RemoveField(
            model_name='orderitemmod',
            name='unit_price_net',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitemmod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
