# Generated by Django 2.1.7 on 2019-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190401_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitemmod',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=386, null=True),
        ),
        migrations.AddField(
            model_name='orderitemmod',
            name='name',
            field=models.CharField(max_length=386, null=True),
        ),
    ]
