# Generated by Django 2.1.7 on 2019-04-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20190401_1611'),
        ('order', '0005_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.Address'),
        ),
    ]
