# Generated by Django 2.1.7 on 2019-04-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190401_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('PLACED', 'placed'), ('VENDOR_ACCEPTED', 'vendor_accepted'), ('VENDOR_PREPARED', 'vendor_prepared'), ('DRIVER_ACCEPTED', 'driver_accepted'), ('DRIVER_CANCELED', 'driver_canceled'), ('DRIVER_PICKED_UP', 'driver_picked_up'), ('DRIVER_DELIVERED', 'driver_delivered'), ('PLACED_FROM_DRAFT', 'draft_placed'), ('OVERSOLD_ITEMS', 'oversold_items'), ('ORDER_MARKED_AS_PAID', 'marked_as_paid'), ('CANCELED', 'canceled'), ('ORDER_FULLY_PAID', 'order_paid'), ('UPDATED', 'updated'), ('EMAIL_SENT', 'email_sent'), ('PAYMENT_AUTHORIZED', 'authorized'), ('PAYMENT_CAPTURED', 'captured'), ('PAYMENT_REFUNDED', 'refunded'), ('PAYMENT_VOIDED', 'voided'), ('FULFILLMENT_CANCELED', 'fulfillment_canceled'), ('FULFILLMENT_RESTOCKED_ITEMS', 'restocked_items'), ('FULFILLMENT_FULFILLED_ITEMS', 'fulfilled_items'), ('TRACKING_UPDATED', 'tracking_updated'), ('NOTE_ADDED', 'note_added'), ('OTHER', 'other')], max_length=255),
        ),
    ]
