# Generated by Django 2.0.4 on 2018-05-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('card_type', models.CharField(blank=True, max_length=20)),
                ('masked_number', models.IntegerField()),
                ('payment_type', models.CharField(blank=True, max_length=10)),
                ('expiration_date', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
