# Generated by Django 2.0.4 on 2018-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paymenttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment',
            field=models.ManyToManyField(blank=True, related_name='payment', to='users.PaymentToken'),
        ),
    ]
