# Generated by Django 2.0.4 on 2018-05-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
