# Generated by Django 2.0.4 on 2018-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180525_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(blank=True, to='users.Address'),
        ),
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.ManyToManyField(blank=True, to='users.Address'),
        ),
    ]
