# Generated by Django 2.0.4 on 2018-06-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180606_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='online',
            field=models.NullBooleanField(default=False),
        ),
    ]
