# Generated by Django 2.0.4 on 2018-06-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180609_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='location',
            field=models.ManyToManyField(blank=True, to='users.Location'),
        ),
    ]
