# Generated by Django 2.0.4 on 2018-06-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180609_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AlterField(
            model_name='driver',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='driver_location', to='users.Location'),
        ),
    ]
