# Generated by Django 2.0.4 on 2018-06-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180609_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
