# Generated by Django 2.0.4 on 2018-06-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180609_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
