# Generated by Django 2.0.4 on 2018-06-11 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180611_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
    ]
