# Generated by Django 2.0.4 on 2018-06-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_vendor_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='online',
        ),
    ]
