# Generated by Django 2.0.4 on 2018-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_driver_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_contact_phone',
            new_name='legal_entity_phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_contact_name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='legal_entity_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='legal_entity_first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='legal_entity_last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
