# Generated by Django 2.0.4 on 2018-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20180621_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='stripe_connect_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='stripe_connect_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
