# Generated by Django 2.0.4 on 2018-06-21 21:47

from django.db import migrations, models
import halalivery.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180621_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='stripe_connect_id',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, upload_to=halalivery.users.models.get_upload_path),
        ),
    ]
