# Generated by Django 2.0.4 on 2018-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_driver_stripe_connect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='companyhouse_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
