# Generated by Django 2.0.7 on 2018-08-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20180628_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='zego_registration_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
