# Generated by Django 2.0.7 on 2018-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_driver_zego_registration_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='zego_registration_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
