# Generated by Django 2.0.7 on 2018-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20180802_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='zego_registration_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
