# Generated by Django 2.0.7 on 2018-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20180802_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='transport_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Car'), (1, 'Motorbike'), (2, 'Bicycle')]),
        ),
    ]
