# Generated by Django 2.1.1 on 2018-09-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20180815_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='online',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
