# Generated by Django 2.1.1 on 2018-09-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_driver_insurance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='insurance_type',
            field=models.CharField(choices=[('zego', 'ZEGO Insurance'), ('other', '3rd party insurance provider'), ('not_required', 'Not required')], max_length=50, null=True),
        ),
    ]
