# Generated by Django 2.1.1 on 2018-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20180918_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='customer_address', to='users.Address'),
        ),
    ]
