# Generated by Django 2.1.2 on 2018-12-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20181209_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
