# Generated by Django 2.1.4 on 2018-12-11 01:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20181209_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
