# Generated by Django 2.1.5 on 2019-03-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_address_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='transport_type',
            field=models.PositiveSmallIntegerField(choices=[('car', 'Car'), ('motorbike', 'Motorbike'), ('bicycle', 'Bicycle')]),
        ),
    ]
