# Generated by Django 2.1.5 on 2019-03-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20190324_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('grocery', 'Grocery')], default='grocery', max_length=32),
        ),
    ]
