# Generated by Django 2.1.7 on 2019-04-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20190401_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='transport_type',
            field=models.CharField(choices=[('car', 'Car'), ('motorbike', 'Motorbike'), ('bicycle', 'Bicycle')], max_length=50, null=True),
        ),
    ]
