# Generated by Django 2.1.7 on 2019-04-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_route', to='order.Order'),
        ),
        migrations.AddField(
            model_name='deliverypartnerjob',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner_jobs', to='order.Order'),
        ),
        migrations.AddField(
            model_name='deliverypartnerdriver',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='delivery.DeliveryPartnerJob'),
        ),
    ]
