# Generated by Django 2.1.7 on 2019-04-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20190401_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='distance_in_miles',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
