# Generated by Django 2.1.7 on 2019-04-01 10:26

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import halalivery.payment


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basket', '0005_auto_20190325_2032'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('charge_status', models.CharField(choices=[('not-charged', 'Not charged'), ('partially-charged', 'Partially charged'), ('fully-charged', 'Fully charged'), ('partially-refunded', 'Partially refunded'), ('fully-refunded', 'Fully refunded')], default='not-charged', max_length=20)),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_first_name', models.CharField(blank=True, max_length=256)),
                ('billing_last_name', models.CharField(blank=True, max_length=256)),
                ('billing_company_name', models.CharField(blank=True, max_length=256)),
                ('billing_address_1', models.CharField(blank=True, max_length=256)),
                ('billing_address_2', models.CharField(blank=True, max_length=256)),
                ('billing_city', models.CharField(blank=True, max_length=256)),
                ('billing_city_area', models.CharField(blank=True, max_length=128)),
                ('billing_postal_code', models.CharField(blank=True, max_length=256)),
                ('billing_country_code', models.CharField(blank=True, max_length=2)),
                ('billing_country_area', models.CharField(blank=True, max_length=256)),
                ('cc_first_digits', models.CharField(blank=True, default='', max_length=6)),
                ('cc_last_digits', models.CharField(blank=True, default='', max_length=4)),
                ('cc_brand', models.CharField(blank=True, default='', max_length=40)),
                ('cc_exp_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cc_exp_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000)])),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='')),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='basket.Basket')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.Order')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('kind', models.CharField(choices=[('auth', 'Authorization'), ('charge', 'Charge'), ('refund', 'Refund'), ('capture', 'Capture'), ('void', 'Void')], max_length=10)),
                ('is_success', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6)),
                ('error', models.CharField(choices=[(halalivery.payment.TransactionError('incorrect_number'), 'incorrect_number'), (halalivery.payment.TransactionError('invalid_number'), 'invalid_number'), (halalivery.payment.TransactionError('incorrect_cvv'), 'incorrect_cvv'), (halalivery.payment.TransactionError('invalid_cvv'), 'invalid_cvv'), (halalivery.payment.TransactionError('incorrect_zip'), 'incorrect_zip'), (halalivery.payment.TransactionError('incorrect_address'), 'incorrect_address'), (halalivery.payment.TransactionError('invalid_expiry_date'), 'invalid_expiry_date'), (halalivery.payment.TransactionError('expired'), 'expired'), (halalivery.payment.TransactionError('processing_error'), 'processing_error'), (halalivery.payment.TransactionError('declined'), 'declined')], max_length=256, null=True)),
                ('gateway_response', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.Payment')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transfer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('transfer_party', models.CharField(choices=[('vendor', 'Vendor'), ('driver', 'Driver')], default='vendor', max_length=10)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('error', models.CharField(choices=[(halalivery.payment.TransferError('incorrect_number'), 'incorrect_number'), (halalivery.payment.TransferError('invalid_number'), 'invalid_number'), (halalivery.payment.TransferError('incorrect_cvv'), 'incorrect_cvv'), (halalivery.payment.TransferError('invalid_cvv'), 'invalid_cvv'), (halalivery.payment.TransferError('incorrect_zip'), 'incorrect_zip'), (halalivery.payment.TransferError('incorrect_address'), 'incorrect_address'), (halalivery.payment.TransferError('invalid_expiry_date'), 'invalid_expiry_date'), (halalivery.payment.TransferError('expired'), 'expired'), (halalivery.payment.TransferError('processing_error'), 'processing_error'), (halalivery.payment.TransferError('declined'), 'declined')], max_length=256, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=6)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('source_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_transaction', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_group', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_response', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='payment.Payment')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
