# Generated by Django 2.1.7 on 2019-04-01 16:26

from django.db import migrations, models
import halalivery.payment


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190401_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='error',
            field=models.CharField(choices=[(halalivery.payment.TransactionError('incorrect_number'), 'incorrect_number'), (halalivery.payment.TransactionError('invalid_number'), 'invalid_number'), (halalivery.payment.TransactionError('incorrect_cvv'), 'incorrect_cvv'), (halalivery.payment.TransactionError('invalid_cvv'), 'invalid_cvv'), (halalivery.payment.TransactionError('incorrect_zip'), 'incorrect_zip'), (halalivery.payment.TransactionError('incorrect_address'), 'incorrect_address'), (halalivery.payment.TransactionError('invalid_expiry_date'), 'invalid_expiry_date'), (halalivery.payment.TransactionError('expired'), 'expired'), (halalivery.payment.TransactionError('processing_error'), 'processing_error'), (halalivery.payment.TransactionError('declined'), 'declined')], max_length=256, null=True),
        ),
    ]
