# Generated by Django 2.1.7 on 2019-04-01 18:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20190401_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transfered_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
    ]
