# Generated by Django 2.1.7 on 2019-04-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='surcharge_amount',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='surcharge_amount',
        ),
    ]
