# Generated by Django 2.1.7 on 2019-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0003_auto_20190401_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='surcharge_threshold',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='surcharge_threshold',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=12),
        ),
    ]
