# Generated by Django 2.1.1 on 2018-10-01 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0037_auto_20180918_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('expires_in', models.DurationField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Vendor')),
            ],
        ),
    ]
