# Generated by Django 2.1.1 on 2018-10-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner_discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerdiscount',
            name='amount',
        ),
        migrations.AlterField(
            model_name='partnerdiscount',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_discount', to='users.Vendor'),
        ),
    ]
