# Generated by Django 2.1.1 on 2018-10-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_discounts', '0002_auto_20181001_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdiscount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=4),
            preserve_default=False,
        ),
    ]
