# Generated by Django 2.1.1 on 2018-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_discounts', '0003_partnerdiscount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerdiscount',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='partnerdiscount',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
