# Generated by Django 2.1.5 on 2019-03-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_discounts', '0004_auto_20181010_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdiscount',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
