# Generated by Django 2.1.5 on 2019-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_discounts', '0005_partnerdiscount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdiscount',
            name='min_amount_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
