# Generated by Django 2.1.5 on 2019-03-25 20:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_discounts', '0006_partnerdiscount_min_amount_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdiscount',
            name='min_amount_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
