# Generated by Django 2.1.7 on 2019-04-01 11:28

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=django_prices.models.MoneyField(currency='GBP', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='menuitemoption',
            name='price',
            field=django_prices.models.MoneyField(currency='GBP', decimal_places=2, max_digits=12),
        ),
    ]
