# Generated by Django 2.1.7 on 2019-04-01 10:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0043_auto_20190324_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.TimeField(blank=True)),
                ('available_to', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverOrderVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicycle_radius', models.DecimalField(decimal_places=2, default=1.5, help_text='Set radius in miles', max_digits=6)),
                ('bicycle_delivery_distance', models.DecimalField(decimal_places=2, default=2.0, help_text='Set distance in miles', max_digits=6)),
                ('motorcycle_radius', models.DecimalField(decimal_places=2, default=7.0, help_text='Set radius in miles', max_digits=6)),
                ('motorcycle_delivery_distance', models.DecimalField(decimal_places=2, default=8.0, help_text='Set distance in miles', max_digits=6)),
                ('car_radius', models.DecimalField(decimal_places=2, default=7.0, help_text='Set radius in miles', max_digits=6)),
                ('car_delivery_distance', models.DecimalField(decimal_places=2, default=8.0, help_text='Set distance in miles', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, default=4.0, max_digits=6)),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, default=6.0, max_digits=6)),
                ('per_mile', models.DecimalField(blank=True, decimal_places=2, default=1.35, max_digits=6)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=6)),
            ],
        ),
    ]
