# Generated by Django 2.1.7 on 2019-04-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayout',
            name='base_miles',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=6),
        ),
    ]
