# Generated by Django 2.1.5 on 2019-03-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
