# Generated by Django 2.1.7 on 2019-04-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20190401_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='total',
        ),
    ]
