# Generated by Django 2.1.7 on 2019-04-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20190401_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='mods',
        ),
        migrations.RemoveField(
            model_name='basketitemmod',
            name='item',
        ),
        migrations.AddField(
            model_name='basketitemmod',
            name='basket_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='basket.BasketItem'),
        ),
    ]
