# Generated by Django 2.1.7 on 2019-04-01 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20190401_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='driver_tip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
